SELECT (CASE WHEN GRADES.GRADE >= 8 THEN STUDENTS.NAME ELSE 'NULL' END) AS NAME , GRADES.GRADE, STUDENTS.MARKS
FROM STUDENTS LEFT OUTER JOIN GRADES
ON STUDENTS.MARKS BETWEEN GRADES.MIN_MARK AND GRADES.MAX_MARK
ORDER BY GRADES.GRADE DESC, STUDENTS.NAME ASC;
